commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("add_listing", views.add_listing, name="add_listing"),
    path("categories", views.get_categories, name="categories"),
    path("categorie/<str:name>", views.categorie, name="categorie"),
    path("<str:username>", views.profile, name="profile")

]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser 
from django.db import models


class User(AbstractUser):
    pass

class Categories(models.Model):
    name = models.CharField(max_length=50, unique=True)
    img = models.ImageField(upload_to="categories/")

class Listings(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    sbid = models.FloatField(default=0.00)
    date = models.DateField()
    active = models.BooleanField(default=True)
    Categorie = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    watch_by = models.ManyToManyField(User, related_name="watchlist")

class Imgs(models.Model):
    url = models.URLField()
    listing = models.ForeignKey(Listings, on_delete=models.CASCADE)

class Bids(models.Model):
    bid = models.FloatField()
    listing = models.ForeignKey(Listings, on_delete=models.CASCADE)

class Comments(models.Model):
    comment = models.TextField()
    listing = models.ForeignKey(Listings, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import *


def index(request):
    
    return render(request, "auctions/index.html",{
        "listings": Listings.objects.filter(active = True)
    })


def add_listing(request):
    pass

def watchlist(request):
    pass


def categorie(request,name):
    pass
    


def profile(request, username):
    pass



# get for htmx

def get_categories(request):

    return render(request , "auctions/categories-nav.html" , {
        "categories" : Categories.objects.all() 
    })


# auth

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

commerce/auctions/templates/auctions/categories-nav.html
<div class="categories">
    {% for categorie in categories %}
    
    <a class="categorie" href="categorie/{{categorie.name}}">
        <img src="{{ categorie.img.url }}" alt="" class="categorie-img">
        <h3>{{ categorie.name }}</h3>
    </a>
    {% endfor %}
</div>

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% block head  %}
{% load static %}
<link rel="stylesheet" href="{% static "auctions/listings.css" %}">
{% endblock  %}
{% block body %}

    <div id="categories" hx-get="/categories" hx-swap="innerHTML" hx-trigger="load">
    </div>
    <hr>
    <h2>Active Listings</h2>
    {% load static %}
    <div class="listings-grid">
        <div class="listing">
            <div class="listing-img">
                <img src="{% static "auctions/imgs/default-listing.png" %}" alt="listing img">
            </div>
            <div class="listing-details">
                <h3> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate, quae!</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio dolor doloribus fugiat nesciunt velit ratione aut eos ad aliquam consectetur?</p>
                <div class="listing-footer">
                    <div>
                        <span class="prix">Prix: 1 $</span>
                        <button class="add-watchlist-btn"><i class="bi bi-heart"></i></button>   
                    </div>
                    <p>xx/xx/2024</p>
                </div>
            </div>
        </div>
        <div class="listing">
            <div class="listing-img">
                <img src="{% static "auctions/imgs/default-listing.png" %}" alt="listing img">
            </div>
            <div class="listing-details">
                <h3> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate, quae!</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio dolor doloribus fugiat nesciunt velit ratione aut eos ad aliquam consectetur?</p>
                <div class="listing-footer">
                    <div>
                        <span class="prix">Prix: 2 $</span>
                        <button class="add-watchlist-btn"><i class="bi bi-heart"></i></button>   
                    </div>
                    <p>xx/xx/2024</p>
                </div>
            </div>
        </div>
        <div class="listing">
            <div class="listing-img">
                <img src="{% static "auctions/imgs/default-listing.png" %}" alt="listing img">
            </div>
            <div class="listing-details">
                <h3> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate, quae!</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio dolor doloribus fugiat nesciunt velit ratione aut eos ad aliquam consectetur?</p>
                <div class="listing-footer">
                    <div>
                        <span class="prix">Prix: 3 $</span>
                        <button class="add-watchlist-btn"><i class="bi bi-heart"></i></button>   
                    </div>
                    <p>xx/xx/2024</p>
                </div>
            </div>
        </div>
        <div class="listing">
            <div class="listing-img">
                <img src="{% static "auctions/imgs/default-listing.png" %}" alt="listing img">
            </div>
            <div class="listing-details">
                <h3> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate, quae!</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio dolor doloribus fugiat nesciunt velit ratione aut eos ad aliquam consectetur?</p>
                <div class="listing-footer">
                    <div>
                        <span class="prix">Prix: 1 $</span>
                        <button class="add-watchlist-btn"><i class="bi bi-heart"></i></button>   
                    </div>
                    <p>xx/xx/2024</p>
                </div>
            </div>
        </div>
        <div class="listing">
            <div class="listing-img">
                <img src="{% static "auctions/imgs/default-listing.png" %}" alt="listing img">
            </div>
            <div class="listing-details">
                <h3> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate, quae!</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio dolor doloribus fugiat nesciunt velit ratione aut eos ad aliquam consectetur?</p>
                <div class="listing-footer">
                    <div>
                        <span class="prix">Prix: 2 $</span>
                        <button class="add-watchlist-btn"><i class="bi bi-heart"></i></button>   
                    </div>
                    <p>xx/xx/2024</p>
                </div>
            </div>
        </div>
        <div class="listing">
            <div class="listing-img">
                <img src="{% static "auctions/imgs/default-listing.png" %}" alt="listing img">
            </div>
            <div class="listing-details">
                <h3> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate, quae!</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio dolor doloribus fugiat nesciunt velit ratione aut eos ad aliquam consectetur?</p>
                <div class="listing-footer">
                    <div>
                        <span class="prix">Prix: 3 $</span>
                        <button class="add-watchlist-btn"><i class="bi bi-heart"></i></button>   
                    </div>
                    <p>xx/xx/2024</p>
                </div>
            </div>
        </div>
    </div>
        <!--
        to test
        <div class="listings-grid">
        {% for listing in listings %}
            <div class="listing">
                {% for img in listing.imgs_set.all %}
                    <div class="listing-img d-none">
                        <button class="listing-img-btn left"><i class="bi bi-arrow-left-circle"></i></button>
                        <img src="{{ img.url }}" alt="listing img">
                        <button class="listing-img-btn right"><i class="bi bi-arrow-right-circle"></i></button>
                    </div>
                {% empty %}
                    <div class="listing-img">
                    <img src="{% static "auctions/imgs/default-listing.png" %}" alt="default listing img">
                    </div>
                {% endfor %}
                <div class="listing-details">
                    <h3>{{ listing.title }}</h3>
                    <p>{{ listing.description }}</p>
                    <div class="listing-footer">
                        <span class="prix">Prix: {{ listing.sbid }}$</span>

                    </div>
                </div>
            </div>
        {% empty %}
            <h3 class=" text-center mt-5 text-white">No Active Listings for now</h3>
        {% endfor %}
        </div>
        -->
    

    
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        {% block head  %}{% endblock  %}
    </head>
    <body>
    <header>
        <nav>
            <a href="/" id="nav-logo">
                <h1>Auctions</h1>
                <p id="nav-user">
                {% if user.is_authenticated %}
                    Signed in as <strong>{{ user.username }}</strong>.
                {% else %}
                    Not signed in.
                {% endif %}
                </p>
            </a>
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
                </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#categories">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item dropdown">
                    <button class="nav-link dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">More</button>
                    
                        <ul class="dropdown-menu" id="dropdown">
                            <li><a class="dropdown-item" href="{% url "add_listing" %}"><i class="bi bi-plus"></i> Add Listing</a></li>
                            <li><a class="dropdown-item" href="/{{ user.username }}"><i class="bi bi-person"></i> Profile</a></li>
                            <li><a class="dropdown-item" href="{% url "logout" %}"><i class="bi bi-box-arrow-left"></i> Logout</a></li>
                        </ul>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        </nav>
        <hr>


        </header>

        <main>
        {% block body %}
        {% endblock %}
        </main>
        <footer></footer>
        <script src="https://unpkg.com/htmx.org@2.0.2" integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

commerce/auctions/templates/auctions/listing.html
    
        <div class="listings-grid">
        {% for listing in listings %}
            <div class="listing">
                {% for img in listing.imgs_set.all %}
                    <div class="listing-img d-none">
                        <button class="listing-img-btn left"><i class="bi bi-arrow-left-circle"></i></button>
                        <img src="{{ img.url }}" alt="listing img">
                        <button class="listing-img-btn right"><i class="bi bi-arrow-right-circle"></i></button>
                    </div>
                {% empty %}
                    <div class="listing-img">
                    <img src="{% static "auctions/imgs/default-listing.png" %}" alt="default listing img">
                    </div>
                {% endfor %}
                <div class="listing-details">
                    <h3>{{ listing.title }}</h3>
                    <p>{{ listing.description }}</p>
                    <div class="listing-footer">
                        <span class="prix">Prix: {{ listing.sbid }}$</span>

                    </div>
                </div>
            </div>
        {% empty %}
            <h3 class=" text-center mt-5 text-white">No Active Listings for now</h3>
        {% endfor %}
        </div>
        <script src="{% static "auctions/js/listings.js" %}" defer></script>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}
{% block head  %}
{% load static %}
<link rel="stylesheet" href="{% static "auctions/auth.html" %}">
{% endblock  %}
{% block body %}

    <div class="auth-form">
        <h2>Login</h2>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="input-label"><i class="bi bi-person"></i></label>
                <input autofocus class="form-control" type="text" name="username" placeholder="Username" id="username">
            </div>
            <div class="form-group">
                <label for="password" class="input-label"><i class="bi bi-key"></i></label>
                <input class="form-control" type="password" name="password" placeholder="Password" id="password">
            </div>
            <input class="btn btn-primary" type="submit" value="Login">
        </form>
        <p>Don't have an account? <a href="{% url 'register' %}">Register here.</a></p>
    </div>


    

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}


    <div class="auth-form">
    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username" class="input-label"><i class="bi bi-person"></i></label>
            <input class="form-control" autofocus type="text" name="username" placeholder="Username" id="username">
        </div>
        <div class="form-group">
            <label for="email" class="input-label"><i class="bi bi-at"></i></label>
            <input class="form-control" type="email" name="email" placeholder="Email Address" id="email">
        </div>
        <div class="form-group">
            <label for="password" class="input-label"><i class="bi bi-key"></i></label>
            <input class="form-control" type="password" name="password" placeholder="Password" id="password">
        </div>
        <div class="form-group">
            <label for="confirmation" class="input-label"><i class="bi bi-check2-circle"></i></label>
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password" id="confirmation">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    <p>Already have an account? <a href="{% url 'login' %}">Log In here.</a></p>
    </div>

{% endblock %}